import propTypes from 'prop-types'
import './globals.css'
import { Providers } from '@/components/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: {
    session,
    // ...params 
  },
}) {

  return (
    <html lang="es">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session}>
          {children}
        </Providers >
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: propTypes.node,
  params: propTypes.object,
}