import propTypes from 'prop-types'
import { Section } from '@/components/atoms/Section'
import {
  ActiveMedications,
  VitalSigns,
  MedicalHistory,
  PatientProfile,
  // MedicalConsultation,
} from '@/components/organisms/'

export const metadata = {
  title: 'Paciente',
  description: 'Generated by create next app',
}

export default function PatientPage({ params: { cedula } }) {
  return (
    <Section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div className="flex flex-col gap-4">
        <PatientProfile cedulaPaciente={cedula} />
        <VitalSigns cedulaPaciente={cedula} />
      </div>
      <div className="flex flex-col gap-4">
        <ActiveMedications cedulaPaciente={cedula} />
        <MedicalHistory cedulaPaciente={cedula} />
      </div>
      {/* <div className="flex flex-col gap-4">
        <MedicalConsultation />
      </div> */}
    </Section>
  )
}

PatientPage.propTypes = {
  params: propTypes.object,
  cedula: propTypes.string,
}
